# Generated by Django 3.1.6 on 2021-02-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_inner'),
    ]

    operations = [
        migrations.AddField(
            model_name='inner',
            name='color',
            field=models.CharField(default='#FFFF', max_length=250),
        ),
    ]
