# Generated by Django 3.1.6 on 2021-02-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_arrivalscontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalscontent',
            name='sortType',
            field=models.CharField(default='*', max_length=20),
        ),
    ]
