# Generated by Django 3.1.6 on 2021-02-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_arrivalscontent_sorttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotsale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('headline', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('original_price', models.FloatField()),
                ('offer_price', models.FloatField()),
            ],
        ),
    ]
