# Generated by Django 3.1.6 on 2021-02-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_hotsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='catogery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('sortType', models.CharField(default='*', max_length=20)),
            ],
        ),
    ]
