# Generated by Django 3.1.6 on 2021-02-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_catogery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catogery',
            new_name='MENS_catogery',
        ),
    ]
